#!/bin/bash

###############################################################################
# MiFi Automated Setup Script
# This script automates the installation and setup of MiFi and all dependencies
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Error tracking
ERRORS=0
WARNINGS=0

# Function to print colored output
print_status() {
    echo -e "${GREEN}[*]${NC} $1"
}

print_error() {
    echo -e "${RED}[!] ERROR:${NC} $1" >&2
    ((ERRORS++))
}

print_warning() {
    echo -e "${YELLOW}[!] WARNING:${NC} $1" >&2
    ((WARNINGS++))
}

print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

# Spinner function for long-running operations
spinner() {
    local pid=$1
    local message=$2
    local spinstr='|/-\'
    local delay=0.1
    
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf "\r${BLUE}[*]${NC} $message ${spinstr:0:1}"
        spinstr=$temp${spinstr%"$temp"}
        sleep $delay
    done
    printf "\r${GREEN}[*]${NC} $message ${GREEN}✓${NC}\n"
}

# Progress bar function (for operations with known duration)
progress_bar() {
    local current=$1
    local total=$2
    local width=50
    local percentage=$((current * 100 / total))
    local filled=$((width * current / total))
    local empty=$((width - filled))
    
    printf "\r${BLUE}[*]${NC} Progress: ["
    printf "%${filled}s" | tr ' ' '='
    printf "%${empty}s" | tr ' ' '-'
    printf "] %d%%" "$percentage"
    
    if [ $current -eq $total ]; then
        printf " ${GREEN}✓${NC}\n"
    fi
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check if running as root
check_root() {
    if [ "$EUID" -eq 0 ]; then
        print_error "This script should NOT be run as root/sudo. It will prompt for sudo when needed."
        exit 1
    fi
}

# Function to create directories
create_directories() {
    print_status "Creating necessary directories..."
    
    DIRS=("logs" "collection" "tak" "config")
    
    for dir in "${DIRS[@]}"; do
        if [ ! -d "$dir" ]; then
            mkdir -p "$dir"
            print_info "Created directory: $dir"
        else
            print_info "Directory already exists: $dir"
        fi
    done
}

# overwatch branch: git-friendly repo. collection/*.cap and config/networks.db
# are the things meant to be pushed/pulled between truck and desktop -- everything
# else here is either regenerable (rockyou.txt) or pure operational noise (logs).
setup_gitignore() {
    print_status "Setting up .gitignore..."

    GITIGNORE_FILE=".gitignore"
    GITIGNORE_CONTENT='# overwatch branch -- auto-generated by start.sh
config/rockyou.txt
logs/
*.potfile
*.netxml
dump*.cap
__pycache__/
*.pyc
'

    if [ -f "$GITIGNORE_FILE" ]; then
        print_info ".gitignore already exists, leaving as-is"
    else
        echo "$GITIGNORE_CONTENT" > "$GITIGNORE_FILE"
        print_info "Created .gitignore"
    fi
}

# Function to create database file
create_database() {
    print_status "Creating database file..."
    
    # Ensure we're in the script directory
    cd "$SCRIPT_DIR"
    
    # Ensure config directory exists
    if [ ! -d "config" ]; then
        mkdir -p "config"
        print_info "Created config directory"
    fi
    
    DB_FILE="config/networks.db"
    
    if [ ! -f "$DB_FILE" ]; then
        touch "$DB_FILE"
        print_info "Created database file: $DB_FILE"
    else
        print_info "Database file already exists: $DB_FILE"
    fi
}

# Function to detect Linux distribution
detect_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO=$ID
        VERSION=$VERSION_ID
    else
        print_error "Cannot detect Linux distribution"
        exit 1
    fi
}

# Function to install system packages
install_system_packages() {
    print_status "Installing system packages (this may require sudo)..."
    
    detect_distro
    
    case $DISTRO in
        ubuntu|debian)
            PACKAGES=(
                "aircrack-ng"
                "john"
                "hashcat"
                "python3"
                "python3-pip"
                "gpsd-clients"
                "iw"
                "wireless-tools"
                "netcat-openbsd"
            )
            
            print_info "Detected: $DISTRO $VERSION"
            print_info "Updating package lists..."
            sudo apt-get update || {
                print_error "Failed to update package lists"
                return 1
            }
            
            MISSING_PACKAGES=()
            for pkg in "${PACKAGES[@]}"; do
                if ! dpkg -l | grep -q "^ii  $pkg "; then
                    MISSING_PACKAGES+=("$pkg")
                fi
            done
            
            if [ ${#MISSING_PACKAGES[@]} -eq 0 ]; then
                print_status "All required packages are already installed"
            else
                print_info "Installing missing packages: ${MISSING_PACKAGES[*]}"
                (sudo apt-get install -y "${MISSING_PACKAGES[@]}" >/dev/null 2>&1) &
                spinner $! "Installing system packages"
                wait $!
                if [ $? -ne 0 ]; then
                    print_error "Failed to install packages"
                    return 1
                fi
            fi
            ;;
        fedora|rhel|centos)
            PACKAGES=(
                "aircrack-ng"
                "john"
                "hashcat"
                "python3"
                "python3-pip"
                "gpsd"
                "gpsd-clients"
                "iw"
                "wireless-tools"
            )
            
            print_info "Detected: $DISTRO $VERSION"
            print_info "Installing packages..."
            (sudo dnf install -y "${PACKAGES[@]}" >/dev/null 2>&1) &
            spinner $! "Installing system packages"
            wait $!
            if [ $? -ne 0 ]; then
                print_error "Failed to install packages"
                return 1
            fi
            ;;
        arch|manjaro)
            PACKAGES=(
                "aircrack-ng"
                "john"
                "hashcat"
                "python"
                "python-pip"
                "gpsd"
                "iw"
                "wireless_tools"
            )
            
            print_info "Detected: $DISTRO"
            print_info "Installing packages..."
            (sudo pacman -S --noconfirm "${PACKAGES[@]}" >/dev/null 2>&1) &
            spinner $! "Installing system packages"
            wait $!
            if [ $? -ne 0 ]; then
                print_error "Failed to install packages"
                return 1
            fi
            ;;
        *)
            print_warning "Unsupported distribution: $DISTRO"
            print_info "Please manually install: aircrack-ng, john, hashcat, python3, gpsd, gpsd-clients, iw, wireless-tools"
            return 1
            ;;
    esac
    
    print_status "System packages installed successfully"
    return 0
}

# Function to install John the Ripper Jumbo (includes wpapcap2john)
install_john_jumbo() {
    print_status "Checking for John the Ripper Jumbo (required for wpapcap2john)..."
    
    # First, ensure PATH includes common installation locations
    export PATH="$PATH:/usr/local/bin:/usr/local/sbin"
    
    # Check if wpapcap2john is already in PATH
    if command_exists wpapcap2john; then
        print_info "wpapcap2john is already available in PATH: $(which wpapcap2john)"
        return 0
    fi
    
    # Check common installation locations
    WPA2JOHN_LOCATIONS=(
        "/usr/local/bin/wpapcap2john"
        "/usr/local/sbin/wpapcap2john"
        "/usr/bin/wpapcap2john"
        "/usr/sbin/wpapcap2john"
        "$HOME/.local/bin/wpapcap2john"
    )
    
    for location in "${WPA2JOHN_LOCATIONS[@]}"; do
        if [ -f "$location" ] && [ -x "$location" ]; then
            print_info "wpapcap2john found at: $location"
            # Add parent directory to PATH if not already there
            PARENT_DIR=$(dirname "$location")
            if [[ ":$PATH:" != *":$PARENT_DIR:"* ]]; then
                PATH_LINE="export PATH=\"\$PATH:$PARENT_DIR\""
                if ! grep -q "$PARENT_DIR" ~/.bashrc 2>/dev/null; then
                    echo "$PATH_LINE" >> ~/.bashrc
                    print_info "Added $PARENT_DIR to PATH in ~/.bashrc"
                fi
                export PATH="$PATH:$PARENT_DIR"
            fi
            if command_exists wpapcap2john; then
                print_status "wpapcap2john is now available"
                return 0
            fi
        fi
    done
    
    # Check if there's an existing build we can use
    EXISTING_BUILDS=(
        "/tmp/john-jumbo/run/wpapcap2john"
        "$HOME/john-jumbo/run/wpapcap2john"
    )
    
    for build_path in "${EXISTING_BUILDS[@]}"; do
        if [ -f "$build_path" ] && [ -x "$build_path" ]; then
            print_info "Found existing wpapcap2john build at: $build_path"
            print_info "Installing to /usr/local/bin..."
            if sudo cp "$build_path" /usr/local/bin/ && sudo chmod +x /usr/local/bin/wpapcap2john; then
                export PATH="$PATH:/usr/local/bin"
                if command_exists wpapcap2john; then
                    print_status "wpapcap2john installed and available"
                    # Add to PATH in shell profile
                    if ! grep -q "/usr/local/bin" ~/.bashrc 2>/dev/null; then
                        echo 'export PATH="$PATH:/usr/local/bin:/usr/local/sbin"' >> ~/.bashrc
                        print_info "Added /usr/local/bin to PATH in ~/.bashrc"
                    fi
                    return 0
                fi
            else
                print_warning "Failed to install from existing build, will compile fresh"
            fi
        fi
    done
    
    # If we get here, wpapcap2john is not installed - proceed with installation
    print_info "wpapcap2john not found - proceeding with installation..."
    
    # Check for build dependencies
    print_info "Checking build dependencies..."
    MISSING_DEPS=()
    if ! command_exists gcc; then
        MISSING_DEPS+=("gcc")
    fi
    if ! command_exists make; then
        MISSING_DEPS+=("make")
    fi
    if ! command_exists git; then
        MISSING_DEPS+=("git")
    fi
    
    detect_distro
    case $DISTRO in
        ubuntu|debian)
            # Check for additional dependencies needed for John the Ripper
            if ! pkg-config --exists openssl 2>/dev/null; then
                MISSING_DEPS+=("libssl-dev")
            fi
            if ! pkg-config --exists zlib 2>/dev/null; then
                MISSING_DEPS+=("zlib1g-dev")
            fi
            # Always include build-essential for complete build tools
            if ! dpkg -l | grep -q "^ii  build-essential "; then
                MISSING_DEPS+=("build-essential")
            fi
            ;;
        fedora|rhel|centos)
            # Check for additional dependencies
            if ! pkg-config --exists openssl 2>/dev/null; then
                MISSING_DEPS+=("openssl-devel")
            fi
            if ! pkg-config --exists zlib 2>/dev/null; then
                MISSING_DEPS+=("zlib-devel")
            fi
            ;;
        arch|manjaro)
            # base-devel includes most build tools
            if ! pkg-config --exists openssl 2>/dev/null; then
                MISSING_DEPS+=("openssl")
            fi
            if ! pkg-config --exists zlib 2>/dev/null; then
                MISSING_DEPS+=("zlib")
            fi
            # Check if base-devel is installed
            if ! pacman -Q base-devel >/dev/null 2>&1; then
                MISSING_DEPS+=("base-devel")
            fi
            ;;
    esac
    
    if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
        print_info "Installing build dependencies: ${MISSING_DEPS[*]}"
        case $DISTRO in
            ubuntu|debian)
                sudo apt-get update || {
                    print_warning "Failed to update package lists, continuing anyway..."
                }
                sudo apt-get install -y "${MISSING_DEPS[@]}" || {
                    print_error "Failed to install build dependencies"
                    return 1
                }
                ;;
            fedora|rhel|centos)
                sudo dnf install -y "${MISSING_DEPS[@]}" || {
                    print_error "Failed to install build dependencies"
                    return 1
                }
                ;;
            arch|manjaro)
                sudo pacman -S --noconfirm "${MISSING_DEPS[@]}" || {
                    print_error "Failed to install build dependencies"
                    return 1
                }
                ;;
            *)
                print_warning "Please manually install: ${MISSING_DEPS[*]}"
                return 1
                ;;
        esac
    fi
    
    # Create temporary directory for build
    BUILD_DIR="/tmp/john-jumbo-build-$$"
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"
    
    print_info "Cloning John the Ripper Jumbo repository..."
    if ! git clone https://github.com/openwall/john -b bleeding-jumbo john-jumbo 2>/dev/null; then
        print_error "Failed to clone John the Ripper Jumbo repository"
        cd "$SCRIPT_DIR"
        rm -rf "$BUILD_DIR"
        return 1
    fi
    
    cd john-jumbo/src
    
    print_info "Configuring build..."
    CONFIGURE_OUTPUT=$(./configure 2>&1)
    CONFIGURE_EXIT=$?
    if [ $CONFIGURE_EXIT -ne 0 ]; then
        print_error "Failed to configure John the Ripper Jumbo"
        print_info "Configure output:"
        echo "$CONFIGURE_OUTPUT" | head -20
        print_info "This may be due to missing dependencies. Common issues:"
        print_info "  - Missing OpenSSL development headers (libssl-dev on Debian/Ubuntu)"
        print_info "  - Missing zlib development headers (zlib1g-dev on Debian/Ubuntu)"
        print_info "  - Missing build-essential package"
        cd "$SCRIPT_DIR"
        rm -rf "$BUILD_DIR"
        return 1
    fi
    
    print_info "Compiling John the Ripper Jumbo (this may take 10-30 minutes)..."
    CPU_COUNT=$(nproc 2>/dev/null || echo "4")
    print_info "Using $CPU_COUNT parallel jobs for compilation..."
    
    # Clean first (silent is fine)
    if ! make -s clean >/dev/null 2>&1; then
        print_warning "make clean had issues, continuing anyway..."
    fi
    
    # Compile with spinner in background
    print_info "Starting compilation..."
    (make -j$CPU_COUNT >/tmp/john-compile-$$.log 2>&1) &
    COMPILE_PID=$!
    
    # Show spinner while compiling
    spinner $COMPILE_PID "Compiling John the Ripper Jumbo"
    wait $COMPILE_PID
    COMPILE_EXIT=$?
    
    # Check if compilation succeeded
    if [ $COMPILE_EXIT -ne 0 ]; then
        print_error "Failed to compile John the Ripper Jumbo"
        print_info "Last 20 lines of compile output:"
        tail -20 /tmp/john-compile-$$.log 2>/dev/null || echo "No log file found"
        cd "$SCRIPT_DIR"
        rm -rf "$BUILD_DIR" /tmp/john-compile-$$.log 2>/dev/null
        return 1
    fi
    
    # Verify compilation succeeded by checking for wpapcap2john
    if [ ! -f "../run/wpapcap2john" ]; then
        print_error "Compilation completed but wpapcap2john not found"
        print_info "Checking for wpapcap2john in build directory..."
        find .. -name "wpapcap2john" -type f 2>/dev/null | head -5
        cd "$SCRIPT_DIR"
        rm -rf "$BUILD_DIR" /tmp/john-compile-$$.log 2>/dev/null
        return 1
    fi
    
    print_status "Compilation completed successfully!"
    rm -f /tmp/john-compile-$$.log 2>/dev/null
    
    print_info "Installing John the Ripper Jumbo..."
    # Try make install, but also manually copy wpapcap2john if needed
    if ! sudo make install >/dev/null 2>&1; then
        print_warning "make install had issues, manually installing wpapcap2john..."
    fi
    
    # Ensure wpapcap2john is installed (make install might not include it)
    if [ -f "../run/wpapcap2john" ]; then
        print_info "Copying wpapcap2john to /usr/local/bin..."
        if sudo cp "../run/wpapcap2john" /usr/local/bin/ && sudo chmod +x /usr/local/bin/wpapcap2john; then
            print_info "wpapcap2john installed to /usr/local/bin"
        else
            print_error "Failed to copy wpapcap2john to /usr/local/bin"
            cd "$SCRIPT_DIR"
            rm -rf "$BUILD_DIR" 2>/dev/null || sudo rm -rf "$BUILD_DIR" 2>/dev/null || true
            return 1
        fi
    else
        print_error "wpapcap2john not found in build directory"
        cd "$SCRIPT_DIR"
        rm -rf "$BUILD_DIR" 2>/dev/null || sudo rm -rf "$BUILD_DIR" 2>/dev/null || true
        return 1
    fi
    
    # Clean up build directory (use sudo if needed for files created during install)
    cd "$SCRIPT_DIR"
    if [ -d "$BUILD_DIR" ]; then
        rm -rf "$BUILD_DIR" 2>/dev/null || sudo rm -rf "$BUILD_DIR" 2>/dev/null || {
            print_warning "Could not fully clean build directory: $BUILD_DIR"
            print_info "You can manually remove it later if needed"
        }
    fi
    
    # Add to PATH in shell profile if not already there
    PATH_LINE='export PATH="$PATH:/usr/local/bin:/usr/local/sbin"'
    if ! grep -q "/usr/local/bin" ~/.bashrc 2>/dev/null; then
        echo "$PATH_LINE" >> ~/.bashrc
        print_info "Added /usr/local/bin to PATH in ~/.bashrc"
    fi
    
    # Also add to .profile for non-interactive shells
    if [ -f ~/.profile ] && ! grep -q "/usr/local/bin" ~/.profile 2>/dev/null; then
        echo "$PATH_LINE" >> ~/.profile
        print_info "Added /usr/local/bin to PATH in ~/.profile"
    fi
    
    # Export for current session
    export PATH="$PATH:/usr/local/bin:/usr/local/sbin"
    
    # Verify installation - check multiple locations
    if command_exists wpapcap2john; then
        print_status "John the Ripper Jumbo installed successfully!"
        print_info "wpapcap2john is now available in PATH: $(which wpapcap2john)"
        return 0
    elif [ -f "/usr/local/bin/wpapcap2john" ]; then
        print_status "John the Ripper Jumbo installed successfully!"
        print_info "wpapcap2john found at /usr/local/bin/wpapcap2john"
        print_info "PATH updated - run 'source ~/.bashrc' or restart terminal to use it"
        return 0
    elif [ -f "/usr/local/sbin/wpapcap2john" ]; then
        print_status "John the Ripper Jumbo installed successfully!"
        print_info "wpapcap2john found at /usr/local/sbin/wpapcap2john"
        print_info "PATH updated - run 'source ~/.bashrc' or restart terminal to use it"
        return 0
    else
        print_warning "wpapcap2john installed but not found in expected locations"
        print_info "Checking for wpapcap2john in build directory..."
        if [ -f "$BUILD_DIR/john-jumbo/run/wpapcap2john" ]; then
            print_info "Found wpapcap2john in build directory, copying to /usr/local/bin..."
            sudo cp "$BUILD_DIR/john-jumbo/run/wpapcap2john" /usr/local/bin/ && \
            sudo chmod +x /usr/local/bin/wpapcap2john && {
                export PATH="$PATH:/usr/local/bin"
                if command_exists wpapcap2john; then
                    print_status "wpapcap2john is now available"
                    return 0
                fi
            }
        fi
        print_warning "You may need to restart your terminal or run: source ~/.bashrc"
        return 1
    fi
}

# Function to install Python packages
install_python_packages() {
    print_status "Installing Python dependencies..."
    
    if ! command_exists python3; then
        print_error "python3 is not installed"
        return 1
    fi
    
    if ! command_exists pip3; then
        print_warning "pip3 not found, attempting to install..."
        detect_distro
        case $DISTRO in
            ubuntu|debian)
                sudo apt-get install -y python3-pip || {
                    print_error "Failed to install pip3"
                    return 1
                }
                ;;
            fedora|rhel|centos)
                sudo dnf install -y python3-pip || {
                    print_error "Failed to install pip3"
                    return 1
                }
                ;;
            arch|manjaro)
                sudo pacman -S --noconfirm python-pip || {
                    print_error "Failed to install pip3"
                    return 1
                }
                ;;
            *)
                print_error "Please install pip3 manually for your distribution"
                return 1
                ;;
        esac
    fi
    
    print_info "Upgrading pip..."
    python3 -m pip install --user --upgrade pip 2>&1 | grep -v "externally-managed-environment" >/dev/null || {
        # Try with --break-system-packages if --user fails
        python3 -m pip install --user --upgrade pip --break-system-packages 2>&1 | grep -v "externally-managed-environment" >/dev/null || {
            print_warning "Failed to upgrade pip, continuing anyway..."
        }
    }
    
    print_info "Installing Python packages from config/requirements.txt..."
    
    # Install packages that require --break-system-packages separately
    # gps3 and flask-cors specifically need this flag on some systems
    CRITICAL_PACKAGES=("gps3>=0.33.3" "flask-cors>=4.0.0")
    OTHER_PACKAGES=("flask>=2.0.0" "tabulate>=0.9.0" "pyserial>=3.5")
    
    # First, try installing all packages with --user
    (python3 -m pip install --user -r config/requirements.txt 2>&1) >/tmp/pip-install-$$.log 2>&1 &
    PIP_PID=$!
    spinner $PIP_PID "Installing Python packages"
    wait $PIP_PID
    PIP_EXIT=$?
    
    # If failed due to externally-managed-environment, use --break-system-packages for all
    if [ $PIP_EXIT -ne 0 ] && grep -q "externally-managed-environment" /tmp/pip-install-$$.log 2>/dev/null; then
        print_warning "User installation blocked, trying with --break-system-packages flag..."
        (python3 -m pip install --user -r config/requirements.txt --break-system-packages 2>&1) >/tmp/pip-install-$$.log 2>&1 &
        PIP_PID=$!
        spinner $PIP_PID "Installing Python packages (system override)"
        wait $PIP_PID
        PIP_EXIT=$?
    fi
    
    # Verify and install critical packages (gps3, flask-cors) with --break-system-packages if needed
    print_info "Verifying critical packages (gps3, flask-cors)..."
    
    # Check gps3
    if ! python3 -c "import gps3" 2>/dev/null; then
        print_info "Installing gps3 with --break-system-packages..."
        (python3 -m pip install --user gps3>=0.33.3 --break-system-packages 2>&1) >/tmp/pip-install-$$.log 2>&1 &
        PIP_PID=$!
        spinner $PIP_PID "Installing gps3"
        wait $PIP_PID
        if [ $? -ne 0 ]; then
            print_warning "Failed to install gps3, but continuing..."
            tail -3 /tmp/pip-install-$$.log 2>/dev/null
        fi
    fi
    
    # Check flask-cors (imports as flask_cors)
    if ! python3 -c "import flask_cors" 2>/dev/null; then
        print_info "Installing flask-cors with --break-system-packages..."
        (python3 -m pip install --user flask-cors>=4.0.0 --break-system-packages 2>&1) >/tmp/pip-install-$$.log 2>&1 &
        PIP_PID=$!
        spinner $PIP_PID "Installing flask-cors"
        wait $PIP_PID
        if [ $? -ne 0 ]; then
            print_warning "Failed to install flask-cors, but continuing..."
            tail -3 /tmp/pip-install-$$.log 2>/dev/null
        fi
    fi
    
    # Final check - verify all packages are installed
    if [ $PIP_EXIT -ne 0 ]; then
        print_error "Failed to install some Python packages"
        print_info "Installation log:"
        tail -15 /tmp/pip-install-$$.log 2>/dev/null
        rm -f /tmp/pip-install-$$.log 2>/dev/null
        return 1
    fi
    
    rm -f /tmp/pip-install-$$.log 2>/dev/null
    
    print_status "Python packages installed successfully"
    return 0
}

# Function to download rockyou.txt
download_rockyou() {
    print_status "Checking for rockyou.txt wordlist..."
    
    # Ensure we're in the script directory
    cd "$SCRIPT_DIR"
    
    # Ensure config directory exists
    if [ ! -d "config" ]; then
        mkdir -p "config"
        print_info "Created config directory"
    fi
    
    if [ -f "config/rockyou.txt" ]; then
        print_info "config/rockyou.txt already exists"
        return 0
    fi
    
    print_info "Downloading rockyou.txt wordlist..."
    
    # Try multiple sources
    ROCKYOU_URLS=(
        "https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt"
        "https://www.scrapmaker.com/data/wordlists/dictionaries/rockyou.txt"
    )
    
    for url in "${ROCKYOU_URLS[@]}"; do
        print_info "Trying: $url"
        if wget -q --show-progress -O config/rockyou.txt "$url" 2>/dev/null || \
           curl -L -o config/rockyou.txt "$url" 2>/dev/null; then
            if [ -f "config/rockyou.txt" ] && [ -s "config/rockyou.txt" ]; then
                print_status "Successfully downloaded config/rockyou.txt"
                return 0
            fi
        fi
    done
    
    print_warning "Failed to download rockyou.txt automatically"
    print_info "You can download it manually from:"
    print_info "  https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt"
    print_info "  Or extract from: /usr/share/wordlists/rockyou.txt.gz (if available)"
    
    # Try to extract from system location
    if [ -f "/usr/share/wordlists/rockyou.txt.gz" ]; then
        print_info "Found system rockyou.txt.gz, extracting..."
        gunzip -c /usr/share/wordlists/rockyou.txt.gz > config/rockyou.txt 2>/dev/null && {
            print_status "Extracted rockyou.txt from system location"
            return 0
        }
    fi
    
    return 1
}

# Function to setup GPS
setup_gps() {
    print_status "Configuring GPS (network gpsd source)..."
    print_info "GPS is provided by a network gpsd service, not a USB GPS device on this machine."
    print_info "This just needs the IP/port of wherever gpsd is actually running."

    # Pull current values out of config.ini if it exists, else use defaults
    GPS_HOST="10.0.0.2"
    GPS_PORT="2947"
    if [ -f "config/config.ini" ]; then
        existing_host=$(awk -F'=' '/^\[GPS\]/{f=1} f&&/^host/{print $2; exit}' config/config.ini | xargs)
        existing_port=$(awk -F'=' '/^\[GPS\]/{f=1} f&&/^port/{print $2; exit}' config/config.ini | xargs)
        [ -n "$existing_host" ] && GPS_HOST="$existing_host"
        [ -n "$existing_port" ] && GPS_PORT="$existing_port"
    fi

    read -p "GPS source IP/host [$GPS_HOST]: " input_host
    read -p "GPS source port [$GPS_PORT]: " input_port
    GPS_HOST="${input_host:-$GPS_HOST}"
    GPS_PORT="${input_port:-$GPS_PORT}"

    # Write the values back into config.ini's [GPS] section
    if [ -f "config/config.ini" ]; then
        python3 - "$GPS_HOST" "$GPS_PORT" << 'PYEOF'
import configparser, sys
host, port = sys.argv[1], sys.argv[2]
config = configparser.ConfigParser()
config.read("config/config.ini")
if "GPS" not in config:
    config["GPS"] = {}
config["GPS"]["host"] = host
config["GPS"]["port"] = port
with open("config/config.ini", "w") as f:
    config.write(f)
PYEOF
        print_info "Saved GPS source to config/config.ini: ${GPS_HOST}:${GPS_PORT}"
    fi

    # Confirm reachability (non-fatal either way — just informational)
    if command_exists nc; then
        if nc -z -w3 "$GPS_HOST" "$GPS_PORT" 2>/dev/null; then
            print_status "GPS source reachable at ${GPS_HOST}:${GPS_PORT}"
            return 0
        else
            print_warning "Cannot reach ${GPS_HOST}:${GPS_PORT} right now. Saved anyway — confirm the gpsd service is running there."
            return 1
        fi
    else
        print_warning "nc not installed, skipping GPS reachability check (non-fatal)"
        return 1
    fi
}


# Function to create config.ini if it doesn't exist
create_config() {
    print_status "Checking configuration file..."
    
    # Ensure we're in the script directory
    cd "$SCRIPT_DIR"
    
    # Ensure config directory exists
    if [ ! -d "config" ]; then
        mkdir -p "config"
        print_info "Created config directory"
    fi
    
    if [ ! -f "config/config.ini" ]; then
        print_info "Creating default config/config.ini..."
        cat > config/config.ini << 'EOF'
[DEFAULT]
# Monitor mode interface candidates (comma-separated)
# The tool will automatically detect and use these interfaces
monitor_candidates = wlan1,wlp0s20f0u2

[GPS]
# overwatch branch: GPS is provided by a network gpsd service (not a local
# USB GPS device attached to this machine). host/port point at wherever
# gpsd is actually running and reachable on your network.
host = 10.0.0.2
port = 2947

[TAK]
# TAK Server Configuration
# Set enabled = true to enable TAK integration
# Certificate files should be placed in the 'tak' folder
# Paths in config.ini are relative to the 'tak' folder (or use absolute paths)
enabled = false
host = 
port = 8087
protocol = tcp
# Certificate-based authentication (leave empty if not using)
# Files should be in the 'tak' folder, e.g., 'MiFi-Scanner.p12' or 'tak/MiFi-Scanner.p12'
cert_file = 
# CA certificate for server verification (recommended but optional)
ca_file = 
# API token authentication (alternative to certificates, leave empty if not using)
api_token = 
EOF
        print_status "Created default config/config.ini"
    else
        print_info "config/config.ini already exists"
    fi
}

# Function to setup TAK configuration
setup_tak_config() {
    print_status "TAK Server Configuration (optional)..."
    
    if [ ! -f "config/config.ini" ]; then
        print_warning "config/config.ini not found, skipping TAK configuration"
        return 0
    fi
    
    while true; do
        read -p "Do you want to configure TAK Server integration? (y/n): " configure_tak
        if [[ "$configure_tak" == "y" ]] || [[ "$configure_tak" == "Y" ]]; then
            break
        elif [[ "$configure_tak" == "n" ]] || [[ "$configure_tak" == "N" ]]; then
            print_info "Skipping TAK configuration"
            return 0
        else
            print_warning "Please enter exactly 'y' or 'n'"
        fi
    done
    
    # Read current config
    TAK_ENABLED=$(grep -E "^enabled\s*=" config/config.ini | grep -i "\[TAK\]" -A 10 | grep "^enabled" | cut -d'=' -f2 | tr -d ' ' || echo "false")
    
    # Enable TAK
    print_info "Enabling TAK integration..."
    sed -i '/^\[TAK\]/,/^\[/ s/^enabled = .*/enabled = true/' config/config.ini || \
    sed -i '/^\[TAK\]/a enabled = true' config/config.ini
    
    # Get TAK host
    read -p "Enter TAK Server hostname or IP address: " tak_host
    if [ -n "$tak_host" ]; then
        sed -i '/^\[TAK\]/,/^\[/ s/^host = .*/host = '"$tak_host"'/' config/config.ini || \
        sed -i '/^\[TAK\]/a host = '"$tak_host"'' config/config.ini
    fi
    
    # Get TAK port
    read -p "Enter TAK Server Streaming port [8087]: " tak_port
    tak_port=${tak_port:-8087}
    sed -i '/^\[TAK\]/,/^\[/ s/^port = .*/port = '"$tak_port"'/' config/config.ini || \
    sed -i '/^\[TAK\]/a port = '"$tak_port"'' config/config.ini
    
    # Get protocol
    read -p "Enter protocol (tcp/udp) [tcp]: " tak_protocol
    tak_protocol=${tak_protocol:-tcp}
    sed -i '/^\[TAK\]/,/^\[/ s/^protocol = .*/protocol = '"$tak_protocol"'/' config/config.ini || \
    sed -i '/^\[TAK\]/a protocol = '"$tak_protocol"'' config/config.ini
    
    # Ask about authentication
    print_info "Certificate files should be placed in the 'tak' folder"
    read -p "Use certificate authentication? (y/n) [n]: " use_certs
    if [[ "$use_certs" =~ ^[Yy]$ ]]; then
        echo ""
        print_info "PKCS#12 Certificate File (.p12) - REQUIRED"
        print_info "  This file contains both your client certificate and private key"
        print_info "  File extension must be .p12 or .pfx"
        print_info "  Example: MiFi-Scanner.p12, lab-field.p12"
        while true; do
            read -p "Enter .p12 certificate filename (will be placed in 'tak' folder) or full path: " cert_file
            if [ -z "$cert_file" ]; then
                print_warning "Certificate file is required. Please enter a filename."
                continue
            fi
            # Validate it's a .p12 or .pfx file
            if [[ ! "$cert_file" =~ \.(p12|pfx)$ ]]; then
                print_warning "Certificate file must have .p12 or .pfx extension"
                read -p "Continue anyway? (y/n): " continue_anyway
                if [[ "$continue_anyway" =~ ^[Yy]$ ]]; then
                    break
                fi
            else
                break
            fi
        done
        
        if [ -n "$cert_file" ]; then
            # If it's not an absolute path, assume it's a filename for the tak folder
            if [[ "$cert_file" != /* ]]; then
                cert_path="tak/$cert_file"
                print_info "Certificate will be expected at: $cert_path"
            else
                cert_path="$cert_file"
            fi
            sed -i '/^\[TAK\]/,/^\[/ s|^cert_file = .*|cert_file = '"$cert_file"'|' config/config.ini || \
            sed -i '/^\[TAK\]/a cert_file = '"$cert_file"'' config/config.ini
        fi
        
        echo ""
        print_info "CA Certificate File (.pem) - RECOMMENDED"
        print_info "  Used to verify the TAK server's certificate for secure connections"
        print_info "  File extension should be .pem, .crt, or .cer"
        print_info "  Example: ca.pem, root.pem"
        print_info "  Note: This is optional but recommended for production use"
        read -p "Enter CA certificate filename (optional, will be placed in 'tak' folder) or full path (press Enter to skip): " ca_file
        if [ -n "$ca_file" ]; then
            if [[ "$ca_file" != /* ]]; then
                ca_path="tak/$ca_file"
                print_info "CA certificate will be expected at: $ca_path"
            else
                ca_path="$ca_file"
            fi
            sed -i '/^\[TAK\]/,/^\[/ s|^ca_file = .*|ca_file = '"$ca_file"'|' config/config.ini || \
            sed -i '/^\[TAK\]/a ca_file = '"$ca_file"'' config/config.ini
        else
            print_info "Skipping CA certificate (server verification will be disabled)"
        fi
    else
        read -p "Use API token authentication? (y/n) [n]: " use_token
        if [[ "$use_token" =~ ^[Yy]$ ]]; then
            read -p "Enter API token: " api_token
            if [ -n "$api_token" ]; then
                sed -i '/^\[TAK\]/,/^\[/ s|^api_token = .*|api_token = '"$api_token"'|' config/config.ini || \
                sed -i '/^\[TAK\]/a api_token = '"$api_token"'' config/config.ini
            fi
        fi
    fi
    
    print_status "TAK configuration saved to config/config.ini"
    print_info "You can edit config/config.ini manually to change TAK settings later"
}

# Function to check WiFi interface
check_wifi_interface() {
    print_status "Checking for WiFi interfaces..."
    
    if command_exists iw; then
        INTERFACES=$(iw dev 2>/dev/null | grep -E "Interface" | awk '{print $2}')
        if [ -z "$INTERFACES" ]; then
            print_warning "No wireless interfaces detected"
            print_info "Make sure your WiFi adapter is connected and drivers are installed"
        else
            print_info "Detected wireless interfaces:"
            for iface in $INTERFACES; do
                echo "  - $iface"
            done
        fi
    else
        print_warning "iw command not found, cannot check interfaces"
    fi
}

# Function to verify installation
verify_installation() {
    print_status "Verifying installation..."
    
    VERIFY_ERRORS=0
    
    # Check Python packages
    print_info "Checking Python packages..."
    python3 -c "import tabulate, serial, gps3, flask" 2>/dev/null || {
        print_error "Some Python packages are missing"
        ((VERIFY_ERRORS++))
    }
    
    # Check system commands
    print_info "Checking system commands..."
    COMMANDS=("aircrack-ng" "airodump-ng" "aireplay-ng" "john" "hashcat")
    for cmd in "${COMMANDS[@]}"; do
        if ! command_exists "$cmd"; then
            print_error "$cmd not found in PATH"
            ((VERIFY_ERRORS++))
        fi
    done
    
    # Check for wpapcap2john (from John the Ripper Jumbo)
    print_info "Checking wpapcap2john..."
    if ! command_exists wpapcap2john; then
        print_error "wpapcap2john not found in PATH (required for WPA handshake analysis)"
        print_info "This tool is part of John the Ripper Jumbo"
        print_info "Run './start.sh' again to install it, or install manually"
        ((VERIFY_ERRORS++))
    else
        print_info "wpapcap2john is available"
    fi
    
    # Check directories
    print_info "Checking directories..."
    DIRS=("logs" "collection" "config")
    for dir in "${DIRS[@]}"; do
        if [ ! -d "$dir" ]; then
            print_error "Directory missing: $dir"
            ((VERIFY_ERRORS++))
        fi
    done
    
    # Check database file
    if [ ! -f "config/networks.db" ]; then
        print_error "Database file missing: config/networks.db"
        ((VERIFY_ERRORS++))
    fi
    
    if [ $VERIFY_ERRORS -eq 0 ]; then
        print_status "Installation verification passed!"
        return 0
    else
        print_error "Installation verification failed with $VERIFY_ERRORS errors"
        return 1
    fi
}

# Main execution
main() {
    echo "=========================================="
    echo "  MiFi Automated Setup Script"
    echo "=========================================="
    echo ""
    
    check_root
    
    print_status "Starting MiFi setup..."
    echo ""
    
    # Step 1: Create directories
    create_directories || print_error "Failed to create directories"
    echo ""
    
    # Step 2: Set up .gitignore
    setup_gitignore || print_error "Failed to set up .gitignore"
    echo ""
    
    # Step 3: Create database file
    create_database || print_error "Failed to create database file"
    echo ""
    
    # Step 5: Install system packages
    install_system_packages || print_error "Failed to install system packages"
    echo ""
    
    # Step 6: Install John the Ripper Jumbo (for wpapcap2john)
    install_john_jumbo || print_warning "John the Ripper Jumbo installation had issues (wpapcap2john may not be available)"
    echo ""
    
    # Step 7: Install Python packages
    install_python_packages || print_error "Failed to install Python packages"
    echo ""
    
    # Step 8: Download rockyou.txt
    download_rockyou || print_warning "rockyou.txt not available (optional)"
    echo ""
    
    # Step 9: Create config
    create_config
    echo ""
    
    # Step 10: Setup GPS
    setup_gps || print_warning "GPS setup incomplete (optional)"
    echo ""
    
    # Step 11: Setup TAK configuration (optional)
    setup_tak_config
    echo ""
    
    # Step 12: Check WiFi interface
    check_wifi_interface
    echo ""
    
    # Step 13: Verify installation
    verify_installation
    echo ""
    
    # Summary
    echo "=========================================="
    echo "  Setup Summary"
    echo "=========================================="
    
    if [ $ERRORS -eq 0 ]; then
        print_status "Setup completed successfully!"
        echo ""
        print_info "Next steps:"
        echo "  1. Configure your WiFi interface (if needed):"
        echo "     sudo python3 mifi.py --mode config"
        echo ""
        echo "  2. Start collecting handshakes:"
        echo "     sudo python3 mifi.py --mode collect-manual"
        echo ""
        echo "  3. Or start the web dashboard:"
        echo "     python3 mifi.py --mode dashboard"
        echo ""
        echo "  4. View help for all options:"
        echo "     python3 mifi.py --help"
        echo ""
    else
        print_error "Setup completed with $ERRORS error(s) and $WARNINGS warning(s)"
        echo ""
        print_info "Please review the errors above and fix them manually"
        echo ""
        exit 1
    fi
    
    if [ $WARNINGS -gt 0 ]; then
        print_warning "There were $WARNINGS warning(s) - review them above"
    fi
}

# Run main function
main